name: Issue
# on issues created or updated
on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  ex1:
    runs-on: ubuntu-latest
    # if issue title is ex1
    if: ${{ github.event.issue.title == 'Ex1' || github.event.issue.title == 'ex1' || github.event.issue.title == '练习1' || github.event.issue.title == '练习一' }}
    steps:
      - uses: actions/checkout@v3
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: .github/ISSUE_TEMPLATE/issue1.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add label
        uses: andymckay/labeler@master
        with:
          add-labels: "exercise1"
      - name: Assign author to issue
        uses: technote-space/assign-author@v1

  ex2:
    runs-on: ubuntu-latest
    # if issue title is ex2
    if: ${{ github.event.issue.title == 'Ex2' || github.event.issue.title == 'ex2' || github.event.issue.title == '练习2' || github.event.issue.title == '练习二' }}
    steps:
      - uses: actions/checkout@v3
      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body-file: .github/ISSUE_TEMPLATE/issue2.md
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add label
        uses: andymckay/labeler@master
        with:
          add-labels: "exercise2"
      - name: Assign author to issue
        uses: technote-space/assign-author@v1
